server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: excluded
          uri: no://op
          predicates:
            - Path=Path=/v1/api/user/internal/**
            - Path=/v1/api/file/internal/**
            - Path=/v1/api/lease/internal/**
        - id: lsm-user
          uri: ${lsm.user.url}
          predicates:
            - Path=/v1/api/user/**
        - id: lsm-user-api-docs
          uri: ${lsm.user.url}/v3/api-docs
          predicates:
            - Path=/v3/api-docs/lsm-user
        - id: lsm-file
          uri: ${lsm.file.url}
          predicates:
            - Path=/v1/api/file/**
        - id: lsm-file-api-docs
          uri: ${lsm.file.url}/v3/api-docs
          predicates:
            - Path=/v3/api-docs/lsm-file
        - id: lsm-lease
          uri: ${lsm.lease.url}
          predicates:
            - Path=/v1/api/lease/**
        - id: lsm-lease-api-docs
          uri: ${lsm.lease.url}/v3/api-docs
          predicates:
            - Path=/v3/api-docs/lsm-lease

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

springdoc:
  swagger-ui:
    path: /
